name: 部署到 Azure Web App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v3

    - name: 部署到 Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'orange-trade'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
